### ISSUE TITLE
Creating Wireframes for the Home Page

### ISSUE THREAD

**Issue by singh-mansi** [siju-s/TradeList#11]
I have created a rough sketch of what the finished UI would look like for our application. Suggestions are welcome. 

![Tradelist_Wireframes_MainPage](https://user-images.githubusercontent.com/70277469/151650980-1b7aed24-6f96-475e-9cbe-61a68cd72909.png)

**Comment by singh-mansi** [comment]
https://mansi624440.invisionapp.com/freehand/Tradelist-Wireframes-MainPage-Ral3MjIAO

here is the link if anybody wants to collaborate or make changes

**Comment by siju-s** [comment]
Few things:
1. Instead of All Categories dropdown, can we just have  the headers **For Sale**, **Job** etc which will show a dropdown when hovered with the corresponding subcategories?
2. On the top right corner, we can have an option to view the account details for the user. (Irrelevant for Sprint 1)
3. Probably a text beside GNV which conveys to the user that they can change the city
