### ISSUE TITLE
Wire frame for create a post

### ISSUE THREAD

**Issue by sharwarimarathe** [siju-s/TradeList#31]
Generate the wire frame for create a post. 
![CreateaPost_Wireframe](https://user-images.githubusercontent.com/32274107/159712863-88015aec-494f-4f58-87fd-a5207acb2e27.png)

**Comment by siju-s** [comment]
IMHO we don't need the following fields since the same is also not present on DB:
1. Type of Exchange
2. Make your posting stand out
3. Youtube video link
4. Personal information fields Email and Phone no. should get pre-populated with seller info and so doesn't require textbox.

If we really need any of the above fields, we can add them later. Let me know what you think.

**Comment by yashincontrol** [comment]
Looks good. Yes, I also think that we don't need those fields as of now. Especially the "Make your posting stand out" because that would require us to write some algorithms.
